# coding: utf-8

import json

#uat.json file generated by UAT_SKOS_master.py --> execfile("UAT_SKOS_to_json.py")
uat_flat = 'uat.json'

f = open(uat_flat, 'r')
data = json.load(f)
f.close()

childrenterms =  data['children']

for i in childrenterms:
    q = i['name']
    d = q.lower().replace(" ","_").replace("(","").replace(")","")
    g = open(d+".json",'wb')
    s = json.dumps(i)
    g.write(s)

    g.close()